### ISSUE TITLE
Updating PRs to follow master

### ISSUE THREAD

**Issue by ojura** [googlecartographer/infrastructure#2]
@SirVer this continues the discussion from https://github.com/googlecartographer/cartographer_ros/pull/574.

> It reruns CI, which blocks everything else from being merged. That slows us down. (...) The merge bot will not merge in this case.

So the negative side is that CI time is potentially wasted, but the upside is that you would get to know that your PR is now broken sooner. What do you think about this tradeoff?

Also, what do you think about having Wally update all PRs (even the not approved ones) when the merging queue is empty and there is CI time to spare? Perhaps it could be opt-in by the PR author. E.g. `@wally keep-up2date`.

> I think this is a wrong mindset. A PR that is not yet ready for being merged should be closed and reopened once it is ready to be merged. Having stale PRs in the queue distracts from what can be made progress on.

Okay. Although, even if a PR fell out of date (and therefore not ready), I would like to get feedback. That's why I think it makes sense to keep it open. But sure, I will take care to close PRs that are not completely ready, or mark them as WIP.

**Comment by SirVer** [comment]
> So the negative side is that CI time is potentially wasted, but the upside is that you would get to know that your PR is now broken sooner. What do you think about this tradeoff?

The main issue is that travis only allows us to run 2 CI's at the same time. So while you get the information that your branch is still working (which you should have reasonable confidence by testing on your machine already), you block other people from getting this information AND you block further merges - which will require to rerun the tests anyways. The information gain is minimal, but the inconvenience of clogging CI is maximal. 

And if you require to run CI on your branch, you can set up Travis for your own fork - which should not count towards our budget.

> Okay. Although, even if a PR fell out of date (and therefore not ready), I would like to get feedback. 

Feedback on the idea should be handled in a RFC. Feedback on the implementation should only be given on stuff that is meant to be merged soon, i.e. in the next few days. Nothing wrong with opening a PR, asking for early implementation feedback, then closing the PR again if the work needs significantly longer and then reopening the PR.

**Comment by ojura** [comment]
> And if you require to run CI on your branch, you can set up Travis for your own fork - which should not count towards our budget.

I already do this, but if a PR is open, all pushes that I do to my branch are also queued in your CI.

I admit that having that `Update branch` button glowing before me is like a huge itch that I want to scratch. It would be very nice if Wally could do automatically it for me in a way that causes minimal delays (i.e. only when the merging queue is empty).

**Comment by SirVer** [comment]
> I already do this, but if a PR is open, all pushes that I do to my branch are also queued in your CI.

Seems simple to avoid: Do not do development in PR branches. If you want to run CI, fork the PR branch, merge master and push to your own private repo.

> admit that having that Update branch button glowing before me is like a huge itch that I want to scratch. 

I can relate to that. Unfortunately, GitHub support let us know that it cannot be disabled :(.

> It would be very nice if Wally could do automatically it for me in a way that causes minimal delays (i.e. only when the merging queue is empty).

Still hard though, because you never know when somebody wants to merge something. So wally can never know when it has "idle time" on CI, really.

**Comment by SirVer** [comment]
Closing this for now. As long as we depend on travis and do not run on Google infrastructure, we simply cannot afford to keep all PRs rebased. This can be revisited in the future.
